[dependencies]
base = "0.11.1"
candb = "https://github.com/vporton/CanDB#no-blob"
nacdb = "0.14.2"
stable-rbtree = "1.0.0"
stable-buffer = "https://github.com/canscale/StableBuffer#v0.2.0"
stablebuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
icrc1 = "0.0.2"
itertools = "0.1.2"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main"
array = "https://github.com/aviate-labs/array.mo#main"
xtendedNumbers = "https://github.com/edjCase/motoko_numbers#v1.1.0"
motoko-lib = "https://github.com/research-ag/motoko-lib#0.7"
map7 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v7.0.0"
sha = "https://github.com/enzoh/motoko-sha#master"
stableheapbtreemap = "1.3.0"
map = "9.0.1"
btree = "https://github.com/canscale/StableHeapBTreeMap#v0.3.3"
xtended-numbers = "0.2.1"
"json.mo" = "https://github.com/vporton/json.mo#master@49612cf3865dc24bca7bb0e8b6fcf275d11a8cb2"
nacdb-reorder = "3.2.0"
cycles-simple = "0.11.0"
stablehashmap = "1.0.0"
candb-multi = "0.11.8"
join-proxy-motoko = "https://github.com/vporton/join-proxy-motoko#master@3582456b29cb81e0e304f7df2a3935da670725f6"
"parser-combinators.mo" = "https://github.com/vporton/parser-combinators.mo#master@f87c9417ab145017fb1f83e19ec2fc45588dbd41"
passport-client = "0.4.9"

[dev-dependencies]
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0"
